from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Optional


class IntentCode(str, Enum):
    WEATHER_TODAY = "WEATHER_TODAY"
    WEATHER_TOMORROW = "WEATHER_TOMORROW"
    WEATHER_DAY_AFTER = "WEATHER_DAY_AFTER"
    WEATHER_SPECIFIC = "WEATHER_SPECIFIC"
    WEATHER_OUT_OF_RANGE = "WEATHER_OUT_OF_RANGE"
    CALENDAR_GENERAL = "CALENDAR_GENERAL"
    TIME_BROADCAST = "TIME_BROADCAST"
    ALARM_VIEW = "ALARM_VIEW"
    ALARM_CREATE = "ALARM_CREATE"
    ALARM_REMINDER = "ALARM_REMINDER"
    ALARM_CANCEL = "ALARM_CANCEL"
    SETTINGS_GENERAL = "SETTINGS_GENERAL"
    SETTINGS_SOUND_DOWN = "SETTINGS_SOUND_DOWN"
    SETTINGS_SOUND_UP = "SETTINGS_SOUND_UP"
    SETTINGS_BRIGHTNESS_DOWN = "SETTINGS_BRIGHTNESS_DOWN"
    SETTINGS_BRIGHTNESS_UP = "SETTINGS_BRIGHTNESS_UP"
    HEALTH_MONITOR_GENERAL = "HEALTH_MONITOR_GENERAL"
    HEALTH_MONITOR_BLOOD_PRESSURE = "HEALTH_MONITOR_BLOOD_PRESSURE"
    HEALTH_MONITOR_BLOOD_OXYGEN = "HEALTH_MONITOR_BLOOD_OXYGEN"
    HEALTH_MONITOR_HEART_RATE = "HEALTH_MONITOR_HEART_RATE"
    HEALTH_MONITOR_BLOOD_SUGAR = "HEALTH_MONITOR_BLOOD_SUGAR"
    HEALTH_MONITOR_BLOOD_LIPIDS = "HEALTH_MONITOR_BLOOD_LIPIDS"
    HEALTH_MONITOR_WEIGHT = "HEALTH_MONITOR_WEIGHT"
    HEALTH_MONITOR_BODY_TEMPERATURE = "HEALTH_MONITOR_BODY_TEMPERATURE"
    HEALTH_MONITOR_HEMOGLOBIN = "HEALTH_MONITOR_HEMOGLOBIN"
    HEALTH_MONITOR_URIC_ACID = "HEALTH_MONITOR_URIC_ACID"
    HEALTH_MONITOR_SLEEP = "HEALTH_MONITOR_SLEEP"
    HEALTH_EVALUATION = "HEALTH_EVALUATION"
    HEALTH_EDUCATION = "HEALTH_EDUCATION"
    HEALTH_PROFILE = "HEALTH_PROFILE"
    HEALTH_DOCTOR_GENERAL = "HEALTH_DOCTOR_GENERAL"
    HEALTH_DOCTOR_SPECIFIC = "HEALTH_DOCTOR_SPECIFIC"
    HEALTH_SPECIALIST = "HEALTH_SPECIALIST"
    MEDICATION_REMINDER_VIEW = "MEDICATION_REMINDER_VIEW"
    MEDICATION_REMINDER_CREATE = "MEDICATION_REMINDER_CREATE"
    FAMILY_DOCTOR_GENERAL = "FAMILY_DOCTOR_GENERAL"
    FAMILY_DOCTOR_CONTACT = "FAMILY_DOCTOR_CONTACT"
    FAMILY_DOCTOR_CALL_AUDIO = "FAMILY_DOCTOR_CALL_AUDIO"
    FAMILY_DOCTOR_CALL_VIDEO = "FAMILY_DOCTOR_CALL_VIDEO"
    ALBUM = "ALBUM"
    COMMUNICATION_GENERAL = "COMMUNICATION_GENERAL"
    COMMUNICATION_CALL_AUDIO = "COMMUNICATION_CALL_AUDIO"
    COMMUNICATION_CALL_VIDEO = "COMMUNICATION_CALL_VIDEO"
    HOME_SERVICE_GENERAL = "HOME_SERVICE_GENERAL"
    HOME_SERVICE_APPLIANCE = "HOME_SERVICE_APPLIANCE"
    HOME_SERVICE_HOUSE = "HOME_SERVICE_HOUSE"
    HOME_SERVICE_WATER_ELECTRIC = "HOME_SERVICE_WATER_ELECTRIC"
    HOME_SERVICE_MATERNAL = "HOME_SERVICE_MATERNAL"
    HOME_SERVICE_DOMESTIC = "HOME_SERVICE_DOMESTIC"
    HOME_SERVICE_FOOT = "HOME_SERVICE_FOOT"
    EDUCATION_GENERAL = "EDUCATION_GENERAL"
    ENTERTAINMENT_GENERAL = "ENTERTAINMENT_GENERAL"
    ENTERTAINMENT_MOVIE = "ENTERTAINMENT_MOVIE"
    ENTERTAINMENT_OPERA = "ENTERTAINMENT_OPERA"
    ENTERTAINMENT_OPERA_SPECIFIC = "ENTERTAINMENT_OPERA_SPECIFIC"
    ENTERTAINMENT_MUSIC = "ENTERTAINMENT_MUSIC"
    ENTERTAINMENT_MUSIC_SPECIFIC = "ENTERTAINMENT_MUSIC_SPECIFIC"
    ENTERTAINMENT_AUDIOBOOK = "ENTERTAINMENT_AUDIOBOOK"
    ENTERTAINMENT_RESUME = "ENTERTAINMENT_RESUME"
    ENTERTAINMENT_PREV_TRACK = "ENTERTAINMENT_PREV_TRACK"
    ENTERTAINMENT_NEXT_TRACK = "ENTERTAINMENT_NEXT_TRACK"
    JOKE_MODE = "JOKE_MODE"
    GAME_DOU_DI_ZHU = "GAME_DOU_DI_ZHU"
    GAME_CHINESE_CHESS = "GAME_CHINESE_CHESS"
    CHAT = "CHAT"
    ENTERTAINMENT_MUSIC_OFF = "ENTERTAINMENT_MUSIC_OFF"
    ENTERTAINMENT_AUDIOBOOK_OFF = "ENTERTAINMENT_AUDIOBOOK_OFF"
    ENTERTAINMENT_OPERA_OFF = "ENTERTAINMENT_OPERA_OFF"
    DEVICE_SCREEN_OFF = "DEVICE_SCREEN_OFF"
    MALL_GENERAL = "MALL_GENERAL"
    MALL_DIGITAL_HEALTH_ROBOT = "MALL_DIGITAL_HEALTH_ROBOT"
    MALL_HEALTH_MONITOR_TERMINAL = "MALL_HEALTH_MONITOR_TERMINAL"
    MALL_SMART_LIFE_TERMINAL = "MALL_SMART_LIFE_TERMINAL"
    MALL_HEALTH_FOOD = "MALL_HEALTH_FOOD"
    MALL_SILVER_PRODUCTS = "MALL_SILVER_PRODUCTS"
    MALL_DAILY_PRODUCTS = "MALL_DAILY_PRODUCTS"
    MALL_ORDERS = "MALL_ORDERS"
    UNKNOWN = "UNKNOWN"


@dataclass(frozen=True)
class IntentDefinition:
    code: IntentCode
    result: str
    requires_target: bool = False
    allows_event: bool = False
    allows_status: bool = False
    description: str = ""


INTENT_DEFINITIONS: dict[IntentCode, IntentDefinition] = {
    IntentCode.WEATHER_TODAY: IntentDefinition(IntentCode.WEATHER_TODAY, "今天天气", True),
    IntentCode.WEATHER_TOMORROW: IntentDefinition(IntentCode.WEATHER_TOMORROW, "明天天气", True),
    IntentCode.WEATHER_DAY_AFTER: IntentDefinition(IntentCode.WEATHER_DAY_AFTER, "后天天气", True),
    IntentCode.WEATHER_SPECIFIC: IntentDefinition(IntentCode.WEATHER_SPECIFIC, "特定日期天气", True),
    IntentCode.WEATHER_OUT_OF_RANGE: IntentDefinition(IntentCode.WEATHER_OUT_OF_RANGE, "我还只能查到15天内的天气哦"),
    IntentCode.CALENDAR_GENERAL: IntentDefinition(IntentCode.CALENDAR_GENERAL, "日期时间和万年历"),
    IntentCode.TIME_BROADCAST: IntentDefinition(IntentCode.TIME_BROADCAST, "播报时间"),
    IntentCode.ALARM_VIEW: IntentDefinition(IntentCode.ALARM_VIEW, "闹钟界面"),
    IntentCode.ALARM_CREATE: IntentDefinition(IntentCode.ALARM_CREATE, "新增闹钟", True, True, True),
    IntentCode.ALARM_REMINDER: IntentDefinition(IntentCode.ALARM_REMINDER, "新增闹钟", True, True, True),
    IntentCode.ALARM_CANCEL: IntentDefinition(IntentCode.ALARM_CANCEL, "取消闹钟", True, True, True),
    IntentCode.SETTINGS_GENERAL: IntentDefinition(IntentCode.SETTINGS_GENERAL, "小雅设置"),
    IntentCode.SETTINGS_SOUND_DOWN: IntentDefinition(IntentCode.SETTINGS_SOUND_DOWN, "声音调低"),
    IntentCode.SETTINGS_SOUND_UP: IntentDefinition(IntentCode.SETTINGS_SOUND_UP, "声音调高"),
    IntentCode.SETTINGS_BRIGHTNESS_DOWN: IntentDefinition(IntentCode.SETTINGS_BRIGHTNESS_DOWN, "亮度调低"),
    IntentCode.SETTINGS_BRIGHTNESS_UP: IntentDefinition(IntentCode.SETTINGS_BRIGHTNESS_UP, "亮度调高"),
    IntentCode.HEALTH_MONITOR_GENERAL: IntentDefinition(IntentCode.HEALTH_MONITOR_GENERAL, "健康监测"),
    IntentCode.HEALTH_MONITOR_BLOOD_PRESSURE: IntentDefinition(IntentCode.HEALTH_MONITOR_BLOOD_PRESSURE, "血压监测", True),
    IntentCode.HEALTH_MONITOR_BLOOD_OXYGEN: IntentDefinition(IntentCode.HEALTH_MONITOR_BLOOD_OXYGEN, "血氧监测", True),
    IntentCode.HEALTH_MONITOR_HEART_RATE: IntentDefinition(IntentCode.HEALTH_MONITOR_HEART_RATE, "心率监测", True),
    IntentCode.HEALTH_MONITOR_BLOOD_SUGAR: IntentDefinition(IntentCode.HEALTH_MONITOR_BLOOD_SUGAR, "血糖监测", True),
    IntentCode.HEALTH_MONITOR_BLOOD_LIPIDS: IntentDefinition(IntentCode.HEALTH_MONITOR_BLOOD_LIPIDS, "血脂监测", True),
    IntentCode.HEALTH_MONITOR_WEIGHT: IntentDefinition(IntentCode.HEALTH_MONITOR_WEIGHT, "体重监测", True),
    IntentCode.HEALTH_MONITOR_BODY_TEMPERATURE: IntentDefinition(IntentCode.HEALTH_MONITOR_BODY_TEMPERATURE, "体温监测", True),
    IntentCode.HEALTH_MONITOR_HEMOGLOBIN: IntentDefinition(IntentCode.HEALTH_MONITOR_HEMOGLOBIN, "血红蛋白监测", True),
    IntentCode.HEALTH_MONITOR_URIC_ACID: IntentDefinition(IntentCode.HEALTH_MONITOR_URIC_ACID, "尿酸监测", True),
    IntentCode.HEALTH_MONITOR_SLEEP: IntentDefinition(IntentCode.HEALTH_MONITOR_SLEEP, "睡眠监测", True),
    IntentCode.HEALTH_EVALUATION: IntentDefinition(IntentCode.HEALTH_EVALUATION, "健康评估", True),
    IntentCode.HEALTH_EDUCATION: IntentDefinition(IntentCode.HEALTH_EDUCATION, "健康科普"),
    IntentCode.HEALTH_PROFILE: IntentDefinition(IntentCode.HEALTH_PROFILE, "健康画像", True),
    IntentCode.HEALTH_DOCTOR_GENERAL: IntentDefinition(IntentCode.HEALTH_DOCTOR_GENERAL, "小雅医生"),
    IntentCode.HEALTH_DOCTOR_SPECIFIC: IntentDefinition(IntentCode.HEALTH_DOCTOR_SPECIFIC, "小雅医生", True),
    IntentCode.HEALTH_SPECIALIST: IntentDefinition(IntentCode.HEALTH_SPECIALIST, "名医问诊"),
    IntentCode.MEDICATION_REMINDER_VIEW: IntentDefinition(IntentCode.MEDICATION_REMINDER_VIEW, "用药计划"),
    IntentCode.MEDICATION_REMINDER_CREATE: IntentDefinition(IntentCode.MEDICATION_REMINDER_CREATE, "用药计划", True),
    IntentCode.FAMILY_DOCTOR_GENERAL: IntentDefinition(IntentCode.FAMILY_DOCTOR_GENERAL, "家庭医生"),
    IntentCode.FAMILY_DOCTOR_CONTACT: IntentDefinition(IntentCode.FAMILY_DOCTOR_CONTACT, "家庭医生", True),
    IntentCode.FAMILY_DOCTOR_CALL_AUDIO: IntentDefinition(IntentCode.FAMILY_DOCTOR_CALL_AUDIO, "家庭医生", True),
    IntentCode.FAMILY_DOCTOR_CALL_VIDEO: IntentDefinition(IntentCode.FAMILY_DOCTOR_CALL_VIDEO, "家庭医生", True),
    IntentCode.ALBUM: IntentDefinition(IntentCode.ALBUM, "小雅相册"),
    IntentCode.COMMUNICATION_GENERAL: IntentDefinition(IntentCode.COMMUNICATION_GENERAL, "小雅通话"),
    IntentCode.COMMUNICATION_CALL_AUDIO: IntentDefinition(IntentCode.COMMUNICATION_CALL_AUDIO, "小雅音频通话", True),
    IntentCode.COMMUNICATION_CALL_VIDEO: IntentDefinition(IntentCode.COMMUNICATION_CALL_VIDEO, "小雅视频通话", True),
    IntentCode.HOME_SERVICE_GENERAL: IntentDefinition(IntentCode.HOME_SERVICE_GENERAL, "小雅预约"),
    IntentCode.HOME_SERVICE_APPLIANCE: IntentDefinition(IntentCode.HOME_SERVICE_APPLIANCE, "家电维修"),
    IntentCode.HOME_SERVICE_HOUSE: IntentDefinition(IntentCode.HOME_SERVICE_HOUSE, "房屋维修"),
    IntentCode.HOME_SERVICE_WATER_ELECTRIC: IntentDefinition(IntentCode.HOME_SERVICE_WATER_ELECTRIC, "水电维修"),
    IntentCode.HOME_SERVICE_MATERNAL: IntentDefinition(IntentCode.HOME_SERVICE_MATERNAL, "母婴服务"),
    IntentCode.HOME_SERVICE_DOMESTIC: IntentDefinition(IntentCode.HOME_SERVICE_DOMESTIC, "家政服务"),
    IntentCode.HOME_SERVICE_FOOT: IntentDefinition(IntentCode.HOME_SERVICE_FOOT, "中医足道"),
    IntentCode.EDUCATION_GENERAL: IntentDefinition(IntentCode.EDUCATION_GENERAL, "小雅教育", True),
    IntentCode.ENTERTAINMENT_GENERAL: IntentDefinition(IntentCode.ENTERTAINMENT_GENERAL, "娱乐管家"),
    IntentCode.ENTERTAINMENT_MOVIE: IntentDefinition(IntentCode.ENTERTAINMENT_MOVIE, "小雅电影"),
    IntentCode.ENTERTAINMENT_OPERA: IntentDefinition(IntentCode.ENTERTAINMENT_OPERA, "小雅曲艺"),
    IntentCode.ENTERTAINMENT_OPERA_SPECIFIC: IntentDefinition(IntentCode.ENTERTAINMENT_OPERA_SPECIFIC, "小雅曲艺", True),
    IntentCode.ENTERTAINMENT_MUSIC: IntentDefinition(IntentCode.ENTERTAINMENT_MUSIC, "小雅音乐"),
    IntentCode.ENTERTAINMENT_MUSIC_SPECIFIC: IntentDefinition(IntentCode.ENTERTAINMENT_MUSIC_SPECIFIC, "小雅音乐", True),
    IntentCode.ENTERTAINMENT_AUDIOBOOK: IntentDefinition(IntentCode.ENTERTAINMENT_AUDIOBOOK, "小雅听书"),
    IntentCode.ENTERTAINMENT_RESUME: IntentDefinition(IntentCode.ENTERTAINMENT_RESUME, "继续播放"),
    IntentCode.ENTERTAINMENT_PREV_TRACK: IntentDefinition(IntentCode.ENTERTAINMENT_PREV_TRACK, "上一首"),
    IntentCode.ENTERTAINMENT_NEXT_TRACK: IntentDefinition(IntentCode.ENTERTAINMENT_NEXT_TRACK, "下一首"),
    IntentCode.JOKE_MODE: IntentDefinition(IntentCode.JOKE_MODE, "笑话模式"),
    IntentCode.GAME_DOU_DI_ZHU: IntentDefinition(IntentCode.GAME_DOU_DI_ZHU, "斗地主"),
    IntentCode.GAME_CHINESE_CHESS: IntentDefinition(IntentCode.GAME_CHINESE_CHESS, "中国象棋"),
    IntentCode.CHAT: IntentDefinition(IntentCode.CHAT, "语音陪伴或聊天"),
    IntentCode.ENTERTAINMENT_MUSIC_OFF: IntentDefinition(IntentCode.ENTERTAINMENT_MUSIC_OFF, "关闭音乐"),
    IntentCode.ENTERTAINMENT_AUDIOBOOK_OFF: IntentDefinition(IntentCode.ENTERTAINMENT_AUDIOBOOK_OFF, "关闭听书"),
    IntentCode.ENTERTAINMENT_OPERA_OFF: IntentDefinition(IntentCode.ENTERTAINMENT_OPERA_OFF, "关闭戏曲"),
    IntentCode.DEVICE_SCREEN_OFF: IntentDefinition(IntentCode.DEVICE_SCREEN_OFF, "息屏"),
    IntentCode.MALL_GENERAL: IntentDefinition(IntentCode.MALL_GENERAL, "商城"),
    IntentCode.MALL_DIGITAL_HEALTH_ROBOT: IntentDefinition(IntentCode.MALL_DIGITAL_HEALTH_ROBOT, "数字健康机器人"),
    IntentCode.MALL_HEALTH_MONITOR_TERMINAL: IntentDefinition(IntentCode.MALL_HEALTH_MONITOR_TERMINAL, "健康监测终端"),
    IntentCode.MALL_SMART_LIFE_TERMINAL: IntentDefinition(IntentCode.MALL_SMART_LIFE_TERMINAL, "智慧生活终端"),
    IntentCode.MALL_HEALTH_FOOD: IntentDefinition(IntentCode.MALL_HEALTH_FOOD, "健康食疗产品"),
    IntentCode.MALL_SILVER_PRODUCTS: IntentDefinition(IntentCode.MALL_SILVER_PRODUCTS, "适老化用品"),
    IntentCode.MALL_DAILY_PRODUCTS: IntentDefinition(IntentCode.MALL_DAILY_PRODUCTS, "日常生活用品"),
    IntentCode.MALL_ORDERS: IntentDefinition(IntentCode.MALL_ORDERS, "订单页面"),
    IntentCode.UNKNOWN: IntentDefinition(IntentCode.UNKNOWN, "未知指令"),
}
